### ISSUE TITLE
RedisFullCheck1.4.8报错

### ISSUE THREAD

**Issue by gxlxiao** [aliyun/redis-full-check#100]
[root@iZs7z01dz0z12dyttz9zn5Z redis-full-check-1.4.8]# ./redis-full-check -s "10.252.120.10:8004;10.252.120.8:8002;10.252.120.9:8003;10.252.120.7:8001;10.252.120.11:8006;10.252.120.12:8005"  -t "10.252.120.7:9001;10.252.120.8:9002;10.252.120.9:9003;10.252.120.10:9004;10.252.120.11:9006;10.252.120.12:9005" --comparemode=1 --comparetimes=1 --qps=10 --batchcount=100  --targetdbtype=1 
[INFO 2021-06-22-15:10:37 main.go:65]: init log success
[ERROR 2021-06-22-15:10:37 main.go:105]: source address[10.252.120.10:8004;10.252.120.8:8002;10.252.120.9:8003;10.252.120.7:8001;10.252.120.11:8006;10.252.120.12:8005] illegal[if type isn't cluster, should only used 1 node. if type is cluster, input list should be all master or all slave: 'master1;master2;master3...' or 'slave1;slave2;slave3...']
panic: source address[10.252.120.10:8004;10.252.120.8:8002;10.252.120.9:8003;10.252.120.7:8001;10.252.120.11:8006;10.252.120.12:8005] illegal[if type isn't cluster, should only used 1 node. if type is cluster, input list should be all master or all slave: 'master1;master2;master3...' or 'slave1;slave2;slave3...']

goroutine 1 [running]:
main.main()
	/home/zhuzhao.cx/RedisFullCheck/src/full_check/main.go:105 +0x1ba9
[root@iZs7z01dz0z12dyttz9zn5Z redis-full-check-1.4.8]#

**Comment by blight19** [comment]
这个报错信息写的比较明白了，要么全配slave要么全配master
