### ISSUE TITLE
[BUG]1.4.8版本mode=1时 panic：interface conversion

### ISSUE THREAD

**Issue by nemo1105** [aliyun/redis-full-check#118]
命令：`./redis-full-check -s host1:port1 -p pass1 -t host2:port2 -m 1`

报错：

```
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 28 [running]:
full_check/common.ValueHelper_List(0x0, 0x0, 0xc4201ae1e0, 0x0, 0x0)
        /home/zhuzhao.cx/RedisFullCheck/src/full_check/common/helper.go:32 +0x16a
full_check/checker.(*FullValueVerifier).CheckFullValueFetchAll(0xc42013c9a0, 0xc4202b6500, 0x9d, 0xa0, 0xc4201ae1e0, 0xc420228100, 0xc4201aa080)
        /home/zhuzhao.cx/RedisFullCheck/src/full_check/checker/full_value_verifier.go:238 +0x334
full_check/checker.(*FullValueVerifier).VerifyOneGroupKeyInfo(0xc42013c9a0, 0xc420112500, 0xa0, 0xa0, 0xc4201ae1e0, 0xc420228100, 0xc4201aa080)
        /home/zhuzhao.cx/RedisFullCheck/src/full_check/checker/full_value_verifier.go:198 +0x13e7
full_check/full_check.(*FullCheck).VerifyAllKeyInfo(0xc420168000, 0xc4201ae180, 0xc4201ae1e0)
        /home/zhuzhao.cx/RedisFullCheck/src/full_check/full_check/full_check.go:408 +0x412
full_check/full_check.(*FullCheck).Start.func4(0xc4201d80d0, 0xc420168000, 0xc4201ae180, 0xc4201ae1e0)
        /home/zhuzhao.cx/RedisFullCheck/src/full_check/full_check/full_check.go:301 +0x65
created by full_check/full_check.(*FullCheck).Start
        /home/zhuzhao.cx/RedisFullCheck/src/full_check/full_check/full_check.go:299 +0x88c
```

不指定m参数的时候正常跑了一次

**Comment by nemo1105** [comment]
补充，m=4的时候，也会报错。其余参数不变。

```
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 25 [running]:
full_check/common.ValueHelper_List(0x0, 0x0, 0xc4201182a0, 0x0, 0x0)
        /home/zhuzhao.cx/RedisFullCheck/src/full_check/common/helper.go:32 +0x16a
full_check/checker.(*FullValueVerifier).CheckFullValueFetchAll(0xc42013c9a0, 0xc42028cb00, 0x9f, 0xa3, 0xc4201182a0, 0xc420222100, 0xc42025a180)
        /home/zhuzhao.cx/RedisFullCheck/src/full_check/checker/full_value_verifier.go:238 +0x334
full_check/checker.(*FullValueVerifier).VerifyOneGroupKeyInfo(0xc42013c9a0, 0xc42028c000, 0xa3, 0xa3, 0xc4201182a0, 0xc420222100, 0xc42025a180)
        /home/zhuzhao.cx/RedisFullCheck/src/full_check/checker/full_value_verifier.go:198 +0x13e7
full_check/full_check.(*FullCheck).VerifyAllKeyInfo(0xc420166000, 0xc420118240, 0xc4201182a0)
        /home/zhuzhao.cx/RedisFullCheck/src/full_check/full_check/full_check.go:408 +0x412
full_check/full_check.(*FullCheck).Start.func4(0xc4201a6180, 0xc420166000, 0xc420118240, 0xc4201182a0)
        /home/zhuzhao.cx/RedisFullCheck/src/full_check/full_check/full_check.go:301 +0x65
created by full_check/full_check.(*FullCheck).Start
        /home/zhuzhao.cx/RedisFullCheck/src/full_check/full_check/full_check.go:299 +0x88c
```
