### ISSUE TITLE
return element[-1] isn't type string[int64]

### ISSUE THREAD

**Issue by iushas** [aliyun/redis-full-check#129]
panic: run PipeRawCommand with commands[type key:{06S}:000085389141; type key:{06S}:000094471288; type key:{06S}:000047206801; type key:{06S}:000038639760; type key:{06S}:000027092302; type key:{06S}:000065903103; type key:{06S}:000070559570; type key:{06S}:000029782345; type key:{06S}:000099536077; type key:{06S}:000041388060; type key:{06S}:000094407227; type key:{06S}:000000329824; type key:{06S}:000072597388; type key:{06S}:000073883904; type key:{06S}:000042022989; type key:{06S}:000036326084] return element[-1] isn't type string[int64]

goroutine 70 [running]:
full_check/checker.(*KeyOutlineVerifier).FetchKeys.func1(0xc000316000, 0xc000406000, 0x100, 0x100, 0xc0000240b0)
	/home/redis/xtk/RedisFullCheck-release-v1.4.10-20230427/src/full_check/checker/key_outline_verifier.go:25 +0x365
created by full_check/checker.(*KeyOutlineVerifier).FetchKeys
	/home/redis/xtk/RedisFullCheck-release-v1.4.10-20230427/src/full_check/checker/key_outline_verifier.go:22 +0x97

源和目标都是cluster，校验的时候抱着个错，能帮忙看看什么问题吗

**Comment by iushas** [comment]
源和目标的版本都是6.2.4
