### ISSUE TITLE
数据校验报错

### ISSUE THREAD

**Issue by zerobeanny** [aliyun/redis-full-check#95]
报错信息：
panic: run PipeRawCommand with commands[strlen ***（key名）; strlen ***（key名）;...（类似的一堆）] return element[WRONGTYPE Operation against a key holding the wrong kind of value] isn't type int64[redis.redisError]
goroutine 40587 [running]:
full_check/checker.(*VerifierBase).FetchTypeAndLen.func2(0xc4202c6000, 0xc420739800, 0xf7, 0xf7, 0xc4212466d0)
	/home/zhuzhao.cx/RedisFullCheck/src/full_check/checker/base.go:63 +0x16b
created by full_check/checker.(*VerifierBase).FetchTypeAndLen
	/home/zhuzhao.cx/RedisFullCheck/src/full_check/checker/base.go:60 +0x414

环境：
源端是一个单实例，目标端是redis cluster
在源端执行strlen ***（key名） 返回正常

**Comment by Rockycc** [comment]
在源端和目的端执行strlen ***（key名） 是否都返回正常？

**Comment by zerobeanny** [comment]
> 在源端和目的端执行strlen ***（key名） 是否都返回正常？

都是正常

**Comment by zerobeanny** [comment]
有没有可能是key过期引起的？

**Comment by shuaishuai8147** [comment]
我也遇到了，不过我这边报的是type的，在源端执行type命令也没报错

**Comment by blight19** [comment]
同报这个错

**Comment by 1209233066** [comment]
同名key 数据类型不一致

> 报错信息： panic: run PipeRawCommand with commands[strlen ***（key名）; strlen ***（key名）;...（类似的一堆）] return element[WRONGTYPE Operation against a key holding the wrong kind of value] isn't type int64[redis.redisError] goroutine 40587 [running]: full_check/checker.(*VerifierBase).FetchTypeAndLen.func2(0xc4202c6000, 0xc420739800, 0xf7, 0xf7, 0xc4212466d0) /home/zhuzhao.cx/RedisFullCheck/src/full_check/checker/base.go:63 +0x16b created by full_check/checker.(*VerifierBase).FetchTypeAndLen /home/zhuzhao.cx/RedisFullCheck/src/full_check/checker/base.go:60 +0x414
> 
> 环境： 源端是一个单实例，目标端是redis cluster 在源端执行strlen ***（key名） 返回正常
